feat: enable CORS for REST API
waku-org/go-waku pull request #1067
Opened 2024-03-22 07:12 UTC by chaitanyaprem

# Description

# Changes

- [ ] ...
- [ ] ...

# Tests

2024-03-22 07:15 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | 2d855f35 | [#1](https://ci.status.im/job/go-waku/job/prs/job/nix-flake/job/PR-1067/1/) | 2024-03-22 07:15:00 | ~1 min | `nix-flake` | [:page_facing_up:`log`](https://ci.status.im/job/go-waku/job/prs/job/nix-flake/job/PR-1067/1/consoleText) |

2024-03-25 12:27 UTC, richard-ramos requested changes
Instead of adding a enableCors function in all endpoints, in https://github.com/waku-org/go-waku/blob/master/cmd/waku/server/rest/waku_rest.go#L41 add the following:
```go
	mux.Use(func(h http.Handler) http.Handler {
		fn := func(w http.ResponseWriter, r *http.Request) {
			w.Header().Set("Access-Control-Allow-Origin", "*")
		}
		return http.HandlerFunc(fn)
	})
```

2024-03-26 05:59 UTC, chaitanyaprem commented
> Instead of adding a enableCors function in all endpoints, in https://github.com/waku-org/go-waku/blob/master/cmd/waku/server/rest/waku_rest.go#L41 add the following:
> 
> ```go
> 	mux.Use(func(h http.Handler) http.Handler {
> 		fn := func(w http.ResponseWriter, r *http.Request) {
> 			w.Header().Set("Access-Control-Allow-Origin", "*")
> 		}
> 		return http.HandlerFunc(fn)
> 	})
> ```

Ah, i was wondering if there was a simpler way to do this. 
Thanks! this is way simple than doing it in every place.

2024-03-26 12:55 UTC, richard-ramos approved these changes

2024-03-26 13:43 UTC, merged