fix(peer-manager): use backoff only on connection errors
waku-org/go-waku pull request #1089
Opened 2024-04-15 20:51 UTC by richard-ramos

# Description
While attempting to debug the issue #1086 I noticed that the backoff period was being applied both to succesful connections and unsuccesful, hence why the test case described in #1086 failed to connect to the only peer defined, because initially with discv5 there's a connection to the peer, and a immediate disconnection due to peers not being subscribed to any shard, but this connection attempt (which was succesful, even if there was an immediate disconnection afterwards) ended up increasing the backoff period.

## Issue

closes #1086

2024-04-15 20:53 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | 43a391d1 | [#1](https://ci.status.im/job/go-waku/job/prs/job/nix-flake/job/PR-1089/1/) | 2024-04-15 20:53:57 | ~1 min | `nix-flake` | [:page_facing_up:`log`](https://ci.status.im/job/go-waku/job/prs/job/nix-flake/job/PR-1089/1/consoleText) |

2024-04-16 02:34 UTC, romanzac requested changes
Thanks for the initial attempt to fix. When I applied your changes, I am getting message delivered at about 4 out of 5 times I run the TestStaticShardingLimits. Even when I remove lines 464, 465:
```
// Wait for discovery
time.Sleep(3 * time.Second)
```	

Besides this behavior, I have much worse outcome when I subscribe to all 1024 topics at the second relay r2. Lines 502-506 at https://github.com/waku-org/go-waku/blob/b562771c6965504bf897cb30a65a9883912367f4/waku/v2/node/wakunode2_test.go Subscriptions would hang.

2024-04-18 11:17 UTC, chaitanyaprem approved these changes
Good Find

LGTM

2024-05-13 05:23 UTC, chaitanyaprem commented
Let us merge this PR as well after resolving conflicts. This would definitely benefit some use-cases in status.

2024-05-13 05:36 UTC, romanzac approved these changes

2024-05-13 19:07 UTC, merged