Fix/filterv2
waku-org/go-waku pull request #722
Opened 2023-09-09 06:51 UTC by chaitanyaprem

# Description
Updated filterv2 proto file as per rfc.

# Changes

- [ ] Updated filterv2 proto file as per rfc
- [ ] Made broadcaster optional feature for FilterLightNode

# Tests
- Ran all unit tests

2023-09-09 06:53 UTC, status-im-auto commented
### Jenkins Builds
| :grey_question: | Commit | :hash: | Finished (UTC) | Duration | Platform | Result |
|-|-|-|-|-|-|-|
| :heavy_check_mark: | 3e5ea69e | [#1](https://ci.status.im/job/go-waku/job/prs/job/nix-flake/job/PR-722/1/) | 2023-09-09 06:53:40 | ~1 min | `nix-flake` | [:page_facing_up:`log`](https://ci.status.im/job/go-waku/job/prs/job/nix-flake/job/PR-722/1/consoleText) |

2023-09-09 11:13 UTC, richard-ramos reviewed
Overall it looks okay, but requires some changes due to MessagePush `pubsub_topic` being optional introducing some unsafety around the handling of that attribute.

But I do think in this case the RFC is not correct, as the message pubsub topic is always known by the full node, since messages in Relay always arrive in a pubsubTopic, so IMO this condition in https://rfc.vac.dev/spec/12/#message-push  `If this message was received on a specific pubsub_topic, it SHOULD be included in the MessagePush` should be removed and make the pubsub_topic required. What do you think, @jm-clius?

2023-09-09 11:13 UTC, richard-ramos commented on waku/v2/protocol/filter/client.go
> +		if !wf.subscriptions.Has(s.Conn().RemotePeer(), *messagePush.PubsubTopic, messagePush.WakuMessage.ContentTopic) {
While I do think that message pushes with optional pubsub topic make no sense, this code here is not safe as it is possible for a peer to send a `nil` pubsub topic.

2023-09-09 11:13 UTC, richard-ramos commented on waku/v2/protocol/filter/client.go
> +				logging.HostID("peerID", s.Conn().RemotePeer()), zap.String("topic", *messagePush.PubsubTopic),
`messagePush.PubsubTopic` can be nil, so this dereference could fail. 
Perhaps we should add something like this in logging/logging.go:
```go

func NullString(key string, value *string) zap.Field {
	v := "<nil>"
	if value != nil {
		v = *value
	}
	return zap.String(key, v)
}
```
and then use instead  `logging.NullString("topic", messagePush.PubsubTopic)`

2023-09-09 11:13 UTC, richard-ramos commented on waku/v2/protocol/filter/client.go
> +		wf.notify(s.Conn().RemotePeer(), *messagePush.PubsubTopic, messagePush.WakuMessage)
Can be `nil`

2023-09-09 12:10 UTC, chaitanyaprem commented
> 

Agreed, since Filter service node will always know on which pubSubTopic the message is received.

2023-09-11 11:28 UTC, jm-clius commented
Two comments here:
1. The `optional` in the protobuf does not always indicate that the field is optional in the protocol. It may be conditionally mandatory, as it is in this case.
2. Indeed, if the filter service node is a relay node, this field is indeed mandatory as the pubsub topic will be known. However, the spec does not mandate the service node to be a relay node or to participate in a pub/sub configuration. Of course, we don't really envision any other types of service nodes, but we should imagine a service node as "privy to a superset of messages", by whichever means. Imagine a cascade of filter nodes, for example, where each service a more precise filter client. This may be a silly setup, but I don't think we should build a restriction on the service node types into the filter protocol. That would be a bleeding concern.

Also note that under certain autosharding assumptions, we _might_ change the spec in future to exclude pubsub topics as it will be implicit in the content topic.

2023-09-11 15:25 UTC, jm-clius requested changes
See my comment elsewhere. I think the `pubsub_topic` field should remain `optional` for `MessagePush` (as it is conditionally mandatory in the protocol)

2023-09-12 12:15 UTC, richard-ramos approved these changes

2023-09-12 12:15 UTC, richard-ramos commented on waku/v2/protocol/filter/client.go
> +			logger.Error("empty pubSub Topic", zap.Error(err))
No err is generated here
```suggestion
			logger.Error("empty pubsub topic")
```

2023-09-12 12:34 UTC, merged